from __future__ import annotations

import re
from dataclasses import dataclass


SCRIPT_COMPONENT = {
    "label": "Flag Prose Tics",
    "callable": "transform",
}


CALLOUT_TYPE = "Prose Tic"
CALLOUT_PREFIX = f"> [!{CALLOUT_TYPE}]"


@dataclass(frozen=True)
class Rule:
    label: str
    pattern: re.Pattern[str]


def _rule(label: str, pattern: str) -> Rule:
    return Rule(label, re.compile(pattern, re.IGNORECASE))


RULES = (
    _rule("not X, but Y construction", r"\bnot\s+(?:just|simply|merely|only)?\s*[^.!?;:\n]{1,80}?,?\s+but\s+(?:also\s+)?[^.!?\n]{1,100}"),
    _rule("not only X, but also Y construction", r"\bnot\s+only\b[^.!?\n]{1,100}?\bbut\s+also\b"),
    _rule("more than just X construction", r"\bmore\s+than\s+(?:just|simply|merely)\b"),
    _rule("from X to Y framing", r"\bfrom\s+[^,.!?;:\n]{1,45}\s+to\s+[^,.!?;:\n]{1,45}"),
    _rule("whether X, Y, or Z construction", r"\bwhether\s+[^.!?\n]{1,60},\s*[^.!?\n]{1,60},?\s+or\s+[^.!?\n]{1,60}"),
    _rule("generic opening", r"\b(?:at\s+its\s+core|in\s+today(?:'s|’s)\s+(?:rapidly\s+)?(?:changing|evolving)\s+world|in\s+an\s+era\s+of)\b"),
    _rule("importance formula", r"\b(?:this\s+(?:underscores|highlights)\s+the\s+importance\s+of|it(?:'s|’s|\s+is)\s+important\s+to\s+note\s+that)\b"),
    _rule("by doing X, we can Y construction", r"\bby\s+[^,.!?\n]{1,60},\s+(?:we|you|they|organizations?|teams?)\s+can\b"),
    _rule("formulaic transition", r"\b(?:ultimately|fundamentally|crucially|importantly),"),
)


TRIPLE = re.compile(
    r"\b([^,.;:!?\n]{2,35}),\s+([^,.;:!?\n]{2,35}),\s+(?:and|or)\s+([^,.;:!?\n]{2,35})(?=[.;:!?]|$)",
    re.IGNORECASE,
)

FENCE = re.compile(r"^\s*(`{3,}|~{3,})")
EXISTING_FLAG = re.compile(r"^\s*>\s*\[!Prose Tic\]", re.IGNORECASE)


def _find_labels(line: str) -> list[str]:
    labels = [rule.label for rule in RULES if rule.pattern.search(line)]
    if TRIPLE.search(line):
        labels.append("possible rhetorical rule of three")
    if line.count("—") >= 2:
        labels.append("multiple em-dash interruptions")
    return labels


def transform(content: str) -> str:
    """Append compatible editorial callouts after lines with possible prose tics.

    The transform is deliberately conservative: it reports patterns for editorial
    review and makes no claim that a passage was generated by AI.
    """
    lines = content.splitlines()
    output: list[str] = []
    in_frontmatter = bool(lines and lines[0].strip() == "---")
    fence_marker: str | None = None

    for index, line in enumerate(lines):
        output.append(line)

        if in_frontmatter:
            if index > 0 and line.strip() == "---":
                in_frontmatter = False
            continue

        fence_match = FENCE.match(line)
        if fence_match:
            marker = fence_match.group(1)[0]
            fence_marker = None if fence_marker == marker else marker
            continue
        if fence_marker or not line.strip() or EXISTING_FLAG.match(line):
            continue

        labels = _find_labels(line)
        if not labels:
            continue

        following_flags: set[str] = set()
        cursor = index + 1
        while cursor < len(lines) and EXISTING_FLAG.match(lines[cursor]):
            following_flags.add(lines[cursor].strip())
            cursor += 1
        for label in labels:
            flag = f"{CALLOUT_PREFIX} {label}."
            if flag not in following_flags:
                output.append(flag)

    return "\n".join(output) + ("\n" if content.endswith("\n") or output else "")
